name: test

on:
  push:
    paths-ignore:
      - 'LICENSE.*'
      - 'README.*'
  pull_request:
    paths-ignore:
      - 'LICENSE.*'
      - 'README.*'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        nim-version:
          - '1.6.0'
          - '1.6.x'
          - 'stable'
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
      - run: sudo apt update -y
      - run: sudo apt install -y llvm-13-dev
      - run: nimble install -Y
      - run: nimble test -Y
      - run: nimble test -Y --threads:on
